args:
  batch_size: A tf.int64 scalar tf.Tensor, representing the number ofconsecutive elements
    of this dataset to combine in a single batch.
  drop_remainder: (Optional.) A tf.bool scalar tf.Tensor, representingwhether the
    last batch should be dropped in the case it has fewer thanbatch_size elements;
    the default behavior is not to drop the smallerbatch.
  row_splits_dtype: The dtype that should be used for the row_splits of anynew ragged
    tensors.  Existing tf.RaggedTensor elements do not have theirrow_splits dtype
    changed.
error_message: tds len error.[Returns need 1 tds]
name: tf.data.experimental.dense_to_ragged_batch
returns: {}
url: https://www.tensorflow.org/api_docs/python/tf/data/experimental/dense_to_ragged_batch
